[package]
name = "sitka"
version = "0.0.1"
edition = "2021"
authors = ["Ivan Leon <i.leonmaldonado@gmail.com>"]
license = "MIT"
homepage = "https://github.com/ielm/sitka"
repository = "https://github.com/ielm/sitka"
description = "Nonlinear data structures for Rust"
readme = "README.md"
keywords = ["data-structures", "tree", "avl", "nonlinear"]
categories = ["data-structures"]

[dependencies]
