[package]
name = "sitka"
version = "0.0.1"
edition = "2021"
authors = ["@ielm"]
license = "MIT"
homepage = "https://github.com/ielm/sitka"
repository = "https://github.com/ielm/sitka"
description = "A set of tree data structures for Rust"

[dependencies]

